FROM node:23-alpine

RUN apk add --no-cache libc6-compat openssl bash

WORKDIR /usr/src/app

ENV NODE_ENV=production

RUN npm install prisma@6.6.0 --save-exact

COPY prisma ./prisma

ENTRYPOINT ["npx", "prisma", "migrate", "deploy"]