import { z } from "zod";

const schema = z.object({
    examSkinScar: z.coerce.string().optional(),
    examSkinTattoo: z.coerce.string().optional(),
    examSkinLesions: z.coerce.string().optional(),
    examEyeEyelids: z.coerce.string().optional(),
    examEyeConjunctiva: z.coerce.string().optional(),
    examEyePupils: z.coerce.string().optional(),
    examEyeCorneas: z.coerce.string().optional(),
    examEyeMotility: z.coerce.string().optional(),
    examEarAuditoryExternal: z.coerce.string().optional(),
    examEarAuricle: z.coerce.string().optional(),
    examEarEardrum: z.coerce.string().optional(),
    examPharynxLips: z.coerce.string().optional(),
    examPharynxTongue: z.coerce.string().optional(),
    examPharynxPharynx: z.coerce.string().optional(),
    examPharynxTonsils: z.coerce.string().optional(),
    examPharynxTeeth: z.coerce.string().optional(),
    examNosePartition: z.coerce.string().optional(),
    examNoseTurbinates: z.coerce.string().optional(),
    examNoseMucousMembranes: z.coerce.string().optional(),
    examNoseParanasalSinuses: z.coerce.string().optional(),
    examNeckThyroid: z.coerce.string().optional(),
    examNeckMobility: z.coerce.string().optional(),
    examChestBreast: z.coerce.string().optional(),
    examChestHeart: z.coerce.string().optional(),
    examChestLungs: z.coerce.string().optional(),
    examChestRibCage: z.coerce.string().optional(),
    examAbdomenViscera: z.coerce.string().optional(),
    examAbdomenAbdominalWall: z.coerce.string().optional(),
    examColumnFlexibility: z.coerce.string().optional(),
    examColumnDeviation: z.coerce.string().optional(),
    examColumnPain: z.coerce.string().optional(),
    examPelvis: z.coerce.string().optional(),
    examPelvisGenitals: z.coerce.string().optional(),
    examLimbVascular: z.coerce.string().optional(),
    examLimbUpper: z.coerce.string().optional(),
    examLimbLower: z.coerce.string().optional(),
    examNeurologicForce: z.coerce.string().optional(),
    examNeurologicSensitivity: z.coerce.string().optional(),
    examNeurologicGait: z.coerce.string().optional(),
    examNeurologicReflex: z.coerce.string().optional(),
})

export default schema;