name: Docker Image Deployment
on:
  push:
    branches:
      - develop

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.x"]
    env:
        NEXTAUTH_URL: 'http://worflow-url.com/'
        NEXTAUTH_SECRET: 'workflow-secret'
        BACKEND_API: 'http://workflow-url.com/'
        AUTH_SIGNIN_URI: 'http://workflow-url.com/'
        AUTH_LOGIN_URI: 'http://workflow-url.com/'
        AUTH_LOGOUT_URI: 'http://workflow-url.com/'
        AUTH_REFRESH_URI: 'http://workflow-url.com/'
        AUTH_CHANGE_PASSWORD_URI: 'http://workflow-url.com/'
        REGISTRO_CIVIL_URI: 'http://workflow-url.com/'
        REGISTRO_CIVIL_TOKEN: 'workflow-secret'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create temporary env file
        run: |
          echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env
          echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env
          echo "BACKEND_API=$BACKEND_API" >> .env
          echo "AUTH_SIGNIN_URI=$AUTH_SIGNIN_URI" >> .env
          echo "AUTH_LOGIN_URI=$AUTH_LOGIN_URI" >> .env
          echo "AUTH_LOGOUT_URI=$AUTH_LOGOUT_URI" >> .env
          echo "AUTH_REFRESH_URI=$AUTH_REFRESH_URI" >> .env
          echo "AUTH_CHANGE_PASSWORD_URI=$AUTH_CHANGE_PASSWORD_URI" >> .env
          echo "REGISTRO_CIVIL_URI=$REGISTRO_CIVIL_URI" >> .env
          echo "REGISTRO_CIVIL_TOKEN=$REGISTRO_CIVIL_TOKEN" >> .env

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_DEV_TAG }} .
        working-directory: .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_DEV_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    strategy:
      fail-fast: false

    steps:
      - name: Check Repository
        uses: actions/checkout@v4

      - name: SSH into server and deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_DEV_HOST }}
          username: ${{ secrets.SERVER_DEV_USERNAME }}
          password: ${{ secrets.SERVER_DEV_PASSWORD }}
          script: |
            cd ${{ secrets.DOCKER_COMPOSE_DIRECTORY }}
            sh ./${{ secrets.DEPLOY_SCRIPT }}.sh